export const images = {

    tab_heart: require('../../assets/icons/tab_heart.png'),
    tab_grid: require('../../assets/icons/tab_grid.png'),
    tab_message: require('../../assets/icons/tab_message.png'),
    tab_ring: require('../../assets/icons/tab_ring.png'),
    tab_ring_2: require('../../assets/icons/tab_ring_2.png'),
    tab_ring_3: require('../../assets/icons/tab_ring_3.png'),
    tab_user: require('../../assets/icons/tab_user.png'),
    tab_user_2: require('../../assets/icons/tab_user_2.png'),
    tab_star: require('../../assets/icons/tab_star.png'),
    tab_round: require('../../assets/icons/tab_round.png'),
    tab_active_heart: require('../../assets/icons/tab_active_heart.png'),
    tab_active_grid: require('../../assets/icons/tab_active_grid.png'),
    tab_active_heart: require('../../assets/icons/tab_active_heart.png'),
    tab_active_msg: require('../../assets/icons/tab_active_msg.png'),

    intro1: require('../../assets/icons/intro1.png'),
    intro2: require('../../assets/icons/intro2.png'),
    intro3: require('../../assets/icons/intro3.png'),

    category1: require('../../assets/icons/category1.png'),
    category2: require('../../assets/icons/category2.png'),
    category3: require('../../assets/icons/category8.png'),
    category4: require('../../assets/icons/category7.png'),
    category5: require('../../assets/icons/category6.png'),
    category6: require('../../assets/icons/category5.png'),
    category7: require('../../assets/icons/category4.png'),
    category8: require('../../assets/icons/category3.png'),

    result: require('../../assets/icons/result.png'),

    icon_users: require('../../assets/icons/users.png'),
    icon_bin: require('../../assets/icons/bin.png'),
    icon_setting: require('../../assets/icons/setting.png'),
    icon_edit: require('../../assets/icons/edit.png'),
    icon_unring: require('../../assets/icons/unring.png'),
    icon_clock: require('../../assets/icons/clock.png'),
    icon_ring: require('../../assets/icons/ring.png'),
    icon_whatsapp: require('../../assets/icons/whatsapp.png'),
    icon_direction: require('../../assets/icons/direction.png'),
    icon_facebook: require('../../assets/icons/facebook.png'),
    icon_gift: require('../../assets/icons/gift.png'),
    icon_mail: require('../../assets/icons/mail.png'),
    icon_messages: require('../../assets/icons/messages.png'),
    icon_world: require('../../assets/icons/world.png'),
    icon_star2: require('../../assets/icons/star2.png'),
    icon_home: require('../../assets/icons/home.png'),
    icon_roundback: require('../../assets/icons/roundback.png'),
    icon_calendar: require('../../assets/icons/calendar.png'),
    icon_doc: require('../../assets/icons/doc.png'),
    icon_background: require('../../assets/icons/background.png'),
    icon_towel: require('../../assets/icons/towel.png'),
    icon_facebook2: require('../../assets/icons/facebook2.png'),
    icon_sheet: require('../../assets/icons/sheet.png'),
    icon_twitter: require('../../assets/icons/twitter.png'),
    icon_gmail: require('../../assets/icons/gmail.png'),
    icon_alarm: require('../../assets/icons/alarm.png'),
    icon_twin: require('../../assets/icons/twin.png'),
    icon_emoji: require('../../assets/icons/emoji.png'),
    icon_pin: require('../../assets/icons/pin.png'),
    icon_smallgift: require('../../assets/icons/smallgift.png'),
    icon_square: require('../../assets/icons/square.png'),
    icon_instagram: require('../../assets/icons/instagram.png'),
    icon_qrcode: require('../../assets/icons/qrcode.png'),
    icon_schedule: require('../../assets/icons/schedule.png'),
    icon_down: require('../../assets/icons/down.png'),
    icon_check1: require('../../assets/icons/check1.png'),
    icon_check2: require('../../assets/icons/check2.png'),
    icon_position: require('../../assets/icons/position.png'),
    icon_menu: require('../../assets/icons/menu.png'),
    icon_oclock: require('../../assets/icons/oclock.png'),
    icon_msg: require('../../assets/icons/msg.png'),
    icon_doublecheck: require('../../assets/icons/doublecheck.png'),
    icon_lightdown: require('../../assets/icons/lightdown.png'),
    icon_share: require('../../assets/icons/share.png'),
    icon_like: require('../../assets/icons/like.png'),
    icon_spot: require('../../assets/icons/spot.png'),
    icon_rating: require('../../assets/icons/rating.png'),
    icon_big_search: require('../../assets/icons/big_search.png'),
    icon_map: require('../../assets/icons/map.png'),
    icon_time: require('../../assets/icons/time.png'),
    icon_ring2: require('../../assets/icons/ring2.png'),
    icon_ring3: require('../../assets/icons/ring3.png'),
    icon_dank: require('../../assets/icons/dank.png'),
    mark_map: require('../../assets/icons/mark.png'),

    img_user: require('../../assets/data/user.webp'),
    img_demo: require('../../assets/data/demo.jpg'),
    img_user2: require('../../assets/data/ninja.png'),

    //social
    logo: require('../../assets/logo.png'),
    img_avatar: require('../../assets/data/user.webp'),

    question_icon: require('../../assets/data/question_icon.png'),

    

    
};
