export const images = {

    logo: require('../../assets/logo.png'),
    intro: require('../../assets/images/intro.png'),
    user: require('../../assets/images/user.png'),
    splash: require('../../assets/images/splash.png'),
    logoIcon: require('../../assets/images/logoIcon.png'),
    menu: require('../../assets/images/menu.png'),
    ring: require('../../assets/images/ring.png'),
    location: require('../../assets/images/location.png'),
    track: require('../../assets/images/track.png'),
    chart: require('../../assets/images/chart.png'),
    news: require('../../assets/images/news.png'),
    position: require('../../assets/images/position1.png'),
    back: require('../../assets/images/back.png'),
    back_black: require('../../assets/images/back_black.png'),

    add: require('../../assets/images/add1.png'),
    layer: require('../../assets/images/layer1.png'),
    direction: require('../../assets/images/direction1.png'),
    locate: require('../../assets/images/locate1.png'),
    lotes: require('../../assets/images/lotes1.png'),
    cultivo: require('../../assets/images/cultivo.png'),
    nota: require('../../assets/images/nota.png'),
    tarea: require('../../assets/images/tarea.png'),
    lote: require('../../assets/images/lote.png'),
    marker: require('../../assets/images/marker.png'),
    search_white: require('../../assets/images/search_white.png'),

    dot1: require('../../assets/images/dot1.png'),
    dot2: require('../../assets/images/dot2.png'),
    dots: require('../../assets/images/dots.png'),
    check: require('../../assets/images/check.png'),
    download: require('../../assets/images/download.png'),
    msg: require('../../assets/images/msg.png'),
    edit: require('../../assets/images/edit.png'),

    tareaW: require('../../assets/images/tarea-white.png'),
    tareaG: require('../../assets/images/tarea-grey.png'),
    map: require('../../assets/images/map.png'),
    square: require('../../assets/images/square.png'),
    pin: require('../../assets/images/pin.png'),
    pause: require('../../assets/images/pause.png'),
    play: require('../../assets/images/play.png'),
    menu_yellow: require('../../assets/images/menu-yellow.png'),
    menu_blue: require('../../assets/images/menu_blue.png'),

    profile: require('../../assets/images/profile.png'),
    members: require('../../assets/images/members.png'),
    calendar: require('../../assets/images/calendar.png'),

    bigCheck: require('../../assets/images/big-check.png'),
    photoAdd: require('../../assets/images/photo-add.png'),

    record: require('../../assets/images/record.png'),

};
